###
# =======================================================
# TESTES PARA A API DE AVENTUREIROS
# =======================================================
# Use a extensão "REST Client" do VSCode para executar estas requisições.
# A separação "###" permite executar cada bloco individualmente.
# =======================================================

###
# 1. CRIAR um novo aventureiro (POST)
# Rota para criar um novo aventureiro.
# O servidor deve responder com status 201 (Created).
POST https://simulador-guilda.vercel.app/aventureiro HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "nome": "José, O Programador",
    "classe": "Mago do JS"
}

###
#Solicita todos os aventureiros
GET http://localhost:3000/aventureiro HTTP/1.1

###
#solicita um aventureiro pelo seu ID
GET http://localhost:3000/aventureiro/2 HTTP/1.1

###
# Faz a atualização de um aventureiro

PUT http://localhost:3000/aventureiro/21 HTTP/1.1
Content-Type: application/json

{
    "nome": "Novo Nome do Aventureiro"
}

###
#Exclui um aventureiro
DELETE http://localhost:3000/aventureiro/12 HTTP/1.1

###
GET http://localhost:3000/guilda HTTP/1.1